For Review
csevier/VariablesHomework pull request #28
Opened 2021-08-28 00:07 UTC by werewolfwun

2021-08-29 17:27 UTC, csevier requested changes
The intent of the homework is to have a compiling  projects whos asserts pass the check.

2021-08-29 17:27 UTC, csevier commented on VariablesHomework/VariablesHomework.cs
> -        }
Hey John, 

This was not the intent of the homework. The Assert.IsTrue statements need to remain as they are the questions.

2021-08-29 17:27 UTC, csevier commented on VariablesHomework/VariablesHomework.cs
> +            Assert.IsTrue(d ==  // Make this pass
This will not compile, or run or pass.

2021-08-29 19:56 UTC, werewolfwun commented
Thanks, Cody.  Working on it now.

Grandkids are gone so I can concentrate.

I talked to John Beach and he gave me some pointers so I am going to try
those.

I have three asserts that are not working and I am trying to debug why.

[image: image.png]

Also, I wanted to let you know the coming week is my last week of work at
my company.  I am resigning from that job (I make more with my Army
Retirement and disability anway 😀)so I can focus full time on this course.

The point is I may not make all the classes the coming week but will
everyone after that, barring misfortune.

Thanks for the review.  I will resubmit later tonight.





On Sun, Aug 29, 2021 at 12:28 PM csevier ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The intent of the homework is to have a compiling projects whos asserts
> pass the check.
> ------------------------------
>
> In VariablesHomework/VariablesHomework.cs
> <https://github.com/csevier/VariablesHomework/pull/28#discussion_r698046264>
> :
>
> > @@ -8,50 +8,56 @@ public class Variables
>          [TestMethod]
>          public void Declaration()
>          {
> -            Assert.IsTrue(number == 25); // Make this pass
> -            Assert.IsTrue(boolean == true); // Make this pass
> -            Assert.IsTrue(decimalValue == 99.9); // Make this pass
> -            Assert.IsTrue(floatingDecimalValue == 25.4f); // Make this pass
> -            Assert.IsTrue(words == "I am a programmer now"); // Make this pass
> -            Assert.IsTrue(character == 'z'); // Make this pass
> -        }
>
> Hey John,
>
> This was not the intent of the homework. The Assert.IsTrue statements need
> to remain as they are the questions.
> ------------------------------
>
> In VariablesHomework/VariablesHomework.cs
> <https://github.com/csevier/VariablesHomework/pull/28#discussion_r698046361>
> :
>
> > @@ -148,7 +154,7 @@ public void Conversion()
>          {
>              int i = 13;
>              double d = i;
> -            Assert.IsTrue(d == /*Answer here*/); // Make this pass
> +            Assert.IsTrue(d ==  // Make this pass
>
> This will not compile, or run or pass.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/csevier/VariablesHomework/pull/28#pullrequestreview-741136722>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APBJGZJAQ7VHRZDDAU2LUG3T7JU2LANCNFSM5C6PPFSA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-08-29 21:08 UTC, werewolfwun commented
[image: image.png]

On Sun, Aug 29, 2021 at 2:56 PM John Masters ***@***.***> wrote:

> Thanks, Cody.  Working on it now.
>
> Grandkids are gone so I can concentrate.
>
> I talked to John Beach and he gave me some pointers so I am going to try
> those.
>
> I have three asserts that are not working and I am trying to debug why.
>
> [image: image.png]
>
> Also, I wanted to let you know the coming week is my last week of work at
> my company.  I am resigning from that job (I make more with my Army
> Retirement and disability anway 😀)so I can focus full time on this course.
>
> The point is I may not make all the classes the coming week but will
> everyone after that, barring misfortune.
>
> Thanks for the review.  I will resubmit later tonight.
>
>
>
>
>
> On Sun, Aug 29, 2021 at 12:28 PM csevier ***@***.***> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> The intent of the homework is to have a compiling projects whos asserts
>> pass the check.
>> ------------------------------
>>
>> In VariablesHomework/VariablesHomework.cs
>> <https://github.com/csevier/VariablesHomework/pull/28#discussion_r698046264>
>> :
>>
>> > @@ -8,50 +8,56 @@ public class Variables
>>          [TestMethod]
>>          public void Declaration()
>>          {
>> -            Assert.IsTrue(number == 25); // Make this pass
>> -            Assert.IsTrue(boolean == true); // Make this pass
>> -            Assert.IsTrue(decimalValue == 99.9); // Make this pass
>> -            Assert.IsTrue(floatingDecimalValue == 25.4f); // Make this pass
>> -            Assert.IsTrue(words == "I am a programmer now"); // Make this pass
>> -            Assert.IsTrue(character == 'z'); // Make this pass
>> -        }
>>
>> Hey John,
>>
>> This was not the intent of the homework. The Assert.IsTrue statements
>> need to remain as they are the questions.
>> ------------------------------
>>
>> In VariablesHomework/VariablesHomework.cs
>> <https://github.com/csevier/VariablesHomework/pull/28#discussion_r698046361>
>> :
>>
>> > @@ -148,7 +154,7 @@ public void Conversion()
>>          {
>>              int i = 13;
>>              double d = i;
>> -            Assert.IsTrue(d == /*Answer here*/); // Make this pass
>> +            Assert.IsTrue(d ==  // Make this pass
>>
>> This will not compile, or run or pass.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/csevier/VariablesHomework/pull/28#pullrequestreview-741136722>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/APBJGZJAQ7VHRZDDAU2LUG3T7JU2LANCNFSM5C6PPFSA>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-08-29 22:15 UTC, werewolfwun reviewed
I resubmitted my homework with the changes

2021-08-30 00:19 UTC, werewolfwun commented
Hey Cody, can I ask you a couple of questions?

Best,

On Sun, Aug 29, 2021 at 4:08 PM John Masters ***@***.***> wrote:

> [image: image.png]
>
> On Sun, Aug 29, 2021 at 2:56 PM John Masters ***@***.***>
> wrote:
>
>> Thanks, Cody.  Working on it now.
>>
>> Grandkids are gone so I can concentrate.
>>
>> I talked to John Beach and he gave me some pointers so I am going to try
>> those.
>>
>> I have three asserts that are not working and I am trying to debug why.
>>
>> [image: image.png]
>>
>> Also, I wanted to let you know the coming week is my last week of work at
>> my company.  I am resigning from that job (I make more with my Army
>> Retirement and disability anway 😀)so I can focus full time on this course.
>>
>> The point is I may not make all the classes the coming week but will
>> everyone after that, barring misfortune.
>>
>> Thanks for the review.  I will resubmit later tonight.
>>
>>
>>
>>
>>
>> On Sun, Aug 29, 2021 at 12:28 PM csevier ***@***.***>
>> wrote:
>>
>>> ***@***.**** requested changes on this pull request.
>>>
>>> The intent of the homework is to have a compiling projects whos asserts
>>> pass the check.
>>> ------------------------------
>>>
>>> In VariablesHomework/VariablesHomework.cs
>>> <https://github.com/csevier/VariablesHomework/pull/28#discussion_r698046264>
>>> :
>>>
>>> > @@ -8,50 +8,56 @@ public class Variables
>>>          [TestMethod]
>>>          public void Declaration()
>>>          {
>>> -            Assert.IsTrue(number == 25); // Make this pass
>>> -            Assert.IsTrue(boolean == true); // Make this pass
>>> -            Assert.IsTrue(decimalValue == 99.9); // Make this pass
>>> -            Assert.IsTrue(floatingDecimalValue == 25.4f); // Make this pass
>>> -            Assert.IsTrue(words == "I am a programmer now"); // Make this pass
>>> -            Assert.IsTrue(character == 'z'); // Make this pass
>>> -        }
>>>
>>> Hey John,
>>>
>>> This was not the intent of the homework. The Assert.IsTrue statements
>>> need to remain as they are the questions.
>>> ------------------------------
>>>
>>> In VariablesHomework/VariablesHomework.cs
>>> <https://github.com/csevier/VariablesHomework/pull/28#discussion_r698046361>
>>> :
>>>
>>> > @@ -148,7 +154,7 @@ public void Conversion()
>>>          {
>>>              int i = 13;
>>>              double d = i;
>>> -            Assert.IsTrue(d == /*Answer here*/); // Make this pass
>>> +            Assert.IsTrue(d ==  // Make this pass
>>>
>>> This will not compile, or run or pass.
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/csevier/VariablesHomework/pull/28#pullrequestreview-741136722>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/APBJGZJAQ7VHRZDDAU2LUG3T7JU2LANCNFSM5C6PPFSA>
>>> .
>>> Triage notifications on the go with GitHub Mobile for iOS
>>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>>> or Android
>>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>>
>>>
>>

2021-09-04 18:08 UTC, closed without merging